# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from leadgen_msgs/LeadgenObstacleOutput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy
import leadgen_msgs.msg
import std_msgs.msg

class LeadgenObstacleOutput(genpy.Message):
  _md5sum = "9d60182ab72336c69a9994033628ca2b"
  _type = "leadgen_msgs/LeadgenObstacleOutput"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# This message is to describe the information of an obstacle

# Header
std_msgs/Header header

# obstacle ID number
int32 id

# obstacle detection sources(optional)
uint16 source_sensor

# obstacle source sensor definition, using bit-wise operations
# A single obstacle can be detected by multiple sensors, and use OR operation as the result
uint16 SENSOR_LIDAR = 1
uint16 SENSOR_VISION = 2
uint16 SENSOR_RADAR = 4

# obstacle type(optional)
uint8 type

# obstacle type definitions
# subject to change

uint8 OBSTACLE_TYPE_UNKNOWN = 0
uint8 OBSTACLE_TYPE_SMALL = 1
uint8 OBSTACLE_TYPE_BIG = 2
uint8 OBSTACLE_TYPE_CAR = 3
uint8 OBSTACLE_TYPE_BUS = 4
uint8 OBSTACLE_TYPE_TRUCK = 5
uint8 OBSTACLE_TYPE_CYCLER = 6
uint8 OBSTACLE_TYPE_PEDESTRIAN = 7
uint8 OBSTACLE_TYPE_PLANT = 8
uint8 OBSTACLE_TYPE_FENCE = 9

# obstacle status(optional)
uint8 status

# obstacle status definitions
# according to Mobileye specs
uint8 OBSTACLE_STATUS_UNDEFINED = 0
uint8 OBSTACLE_STATUS_STANDING = 1
uint8 OBSTACLE_STATUS_STOPPED = 2
uint8 OBSTACLE_STATUS_MOVING = 3
uint8 OBSTACLE_STATUS_ONCOMING = 4
uint8 OBSTACLE_STATUS_PARKED = 5
uint8 OBSTACLE_STATUS_UNUSED = 6

# obstacle cutting(optional)
uint8 cutting

# obstacle cutting definitions
# according to Mobileye specs
uint8 OBSTACLE_CUTTING_UNDEFINED = 0
uint8 OBSTACLE_IN_HOST_LANE = 1
uint8 OBSTACLE_OUT_HOST_LANE = 2
uint8 OBSTACLE_CUTTING_IN = 3
uint8 OBSTACLE_CUTTING_OUT = 4

# obstacle size
float32 length  # along obstacle's +x direction, in [m] meter
float32 width   # along obstacle's +y direction, in [m]
float32 height  # along obstacle's +z direction, in [m]

float32 velocity_heading # the velocity heading in the world frame

# obstacle pose in body frame
bool rlt_valid  # relative information valid
geometry_msgs/Point rlt_position    # relative position to body frame
float32 rlt_theta   # relative theta angle, to body frame along z axis

# obstacle velocity in body frame
geometry_msgs/Vector3 rlt_velocity  # relative velocity to body frame 

# obstacle pose in world frame
bool abs_valid  # absolute information valid
geometry_msgs/Point abs_position    # absolute position in world frame
float32 abs_theta   # absolute yaw angle in world frame

# obstacle velocity in world frame
geometry_msgs/Vector3 abs_velocity  # absolute velocity in world frame

# decision tags
uint8 longitude_tag
uint8 lateral_tag

# decision tag definitions
uint8 IGNORE = 0 
uint8 STAY_BEHIND = 1

uint8 NUDGE_LEFT = 2   
uint8 NUDGE_RIGHT = 3 
uint8 NOT_AVAILABLE = 4 

LeadgenWaypoint[] predicted_traj
float32 predicted_period


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: leadgen_msgs/LeadgenWaypoint
# This message is to describe a WAYPOINT in the target trajectory

# header
# std_msgs/Header header

# 3D position
geometry_msgs/Point point

# trace info
float64 theta # the heading of the trace at this point
float64 kappa # the curvature of the trace at this point

# SL info
float64 station
float64 lateral

# speed info
float32 speed # in [m/s]
float32 accel # in [m/s^2],(optional)

time time_arrival # the expected arrival time of this point


"""
  # Pseudo-constants
  SENSOR_LIDAR = 1
  SENSOR_VISION = 2
  SENSOR_RADAR = 4
  OBSTACLE_TYPE_UNKNOWN = 0
  OBSTACLE_TYPE_SMALL = 1
  OBSTACLE_TYPE_BIG = 2
  OBSTACLE_TYPE_CAR = 3
  OBSTACLE_TYPE_BUS = 4
  OBSTACLE_TYPE_TRUCK = 5
  OBSTACLE_TYPE_CYCLER = 6
  OBSTACLE_TYPE_PEDESTRIAN = 7
  OBSTACLE_TYPE_PLANT = 8
  OBSTACLE_TYPE_FENCE = 9
  OBSTACLE_STATUS_UNDEFINED = 0
  OBSTACLE_STATUS_STANDING = 1
  OBSTACLE_STATUS_STOPPED = 2
  OBSTACLE_STATUS_MOVING = 3
  OBSTACLE_STATUS_ONCOMING = 4
  OBSTACLE_STATUS_PARKED = 5
  OBSTACLE_STATUS_UNUSED = 6
  OBSTACLE_CUTTING_UNDEFINED = 0
  OBSTACLE_IN_HOST_LANE = 1
  OBSTACLE_OUT_HOST_LANE = 2
  OBSTACLE_CUTTING_IN = 3
  OBSTACLE_CUTTING_OUT = 4
  IGNORE = 0
  STAY_BEHIND = 1
  NUDGE_LEFT = 2
  NUDGE_RIGHT = 3
  NOT_AVAILABLE = 4

  __slots__ = ['header','id','source_sensor','type','status','cutting','length','width','height','velocity_heading','rlt_valid','rlt_position','rlt_theta','rlt_velocity','abs_valid','abs_position','abs_theta','abs_velocity','longitude_tag','lateral_tag','predicted_traj','predicted_period']
  _slot_types = ['std_msgs/Header','int32','uint16','uint8','uint8','uint8','float32','float32','float32','float32','bool','geometry_msgs/Point','float32','geometry_msgs/Vector3','bool','geometry_msgs/Point','float32','geometry_msgs/Vector3','uint8','uint8','leadgen_msgs/LeadgenWaypoint[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,source_sensor,type,status,cutting,length,width,height,velocity_heading,rlt_valid,rlt_position,rlt_theta,rlt_velocity,abs_valid,abs_position,abs_theta,abs_velocity,longitude_tag,lateral_tag,predicted_traj,predicted_period

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LeadgenObstacleOutput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.source_sensor is None:
        self.source_sensor = 0
      if self.type is None:
        self.type = 0
      if self.status is None:
        self.status = 0
      if self.cutting is None:
        self.cutting = 0
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.velocity_heading is None:
        self.velocity_heading = 0.
      if self.rlt_valid is None:
        self.rlt_valid = False
      if self.rlt_position is None:
        self.rlt_position = geometry_msgs.msg.Point()
      if self.rlt_theta is None:
        self.rlt_theta = 0.
      if self.rlt_velocity is None:
        self.rlt_velocity = geometry_msgs.msg.Vector3()
      if self.abs_valid is None:
        self.abs_valid = False
      if self.abs_position is None:
        self.abs_position = geometry_msgs.msg.Point()
      if self.abs_theta is None:
        self.abs_theta = 0.
      if self.abs_velocity is None:
        self.abs_velocity = geometry_msgs.msg.Vector3()
      if self.longitude_tag is None:
        self.longitude_tag = 0
      if self.lateral_tag is None:
        self.lateral_tag = 0
      if self.predicted_traj is None:
        self.predicted_traj = []
      if self.predicted_period is None:
        self.predicted_period = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.source_sensor = 0
      self.type = 0
      self.status = 0
      self.cutting = 0
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.velocity_heading = 0.
      self.rlt_valid = False
      self.rlt_position = geometry_msgs.msg.Point()
      self.rlt_theta = 0.
      self.rlt_velocity = geometry_msgs.msg.Vector3()
      self.abs_valid = False
      self.abs_position = geometry_msgs.msg.Point()
      self.abs_theta = 0.
      self.abs_velocity = geometry_msgs.msg.Vector3()
      self.longitude_tag = 0
      self.lateral_tag = 0
      self.predicted_traj = []
      self.predicted_period = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_iH3B4fB3df3dB3df3d2B().pack(_x.id, _x.source_sensor, _x.type, _x.status, _x.cutting, _x.length, _x.width, _x.height, _x.velocity_heading, _x.rlt_valid, _x.rlt_position.x, _x.rlt_position.y, _x.rlt_position.z, _x.rlt_theta, _x.rlt_velocity.x, _x.rlt_velocity.y, _x.rlt_velocity.z, _x.abs_valid, _x.abs_position.x, _x.abs_position.y, _x.abs_position.z, _x.abs_theta, _x.abs_velocity.x, _x.abs_velocity.y, _x.abs_velocity.z, _x.longitude_tag, _x.lateral_tag))
      length = len(self.predicted_traj)
      buff.write(_struct_I.pack(length))
      for val1 in self.predicted_traj:
        _v1 = val1.point
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_4d2f().pack(_x.theta, _x.kappa, _x.station, _x.lateral, _x.speed, _x.accel))
        _v2 = val1.time_arrival
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
      buff.write(_get_struct_f().pack(self.predicted_period))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rlt_position is None:
        self.rlt_position = geometry_msgs.msg.Point()
      if self.rlt_velocity is None:
        self.rlt_velocity = geometry_msgs.msg.Vector3()
      if self.abs_position is None:
        self.abs_position = geometry_msgs.msg.Point()
      if self.abs_velocity is None:
        self.abs_velocity = geometry_msgs.msg.Vector3()
      if self.predicted_traj is None:
        self.predicted_traj = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 133
      (_x.id, _x.source_sensor, _x.type, _x.status, _x.cutting, _x.length, _x.width, _x.height, _x.velocity_heading, _x.rlt_valid, _x.rlt_position.x, _x.rlt_position.y, _x.rlt_position.z, _x.rlt_theta, _x.rlt_velocity.x, _x.rlt_velocity.y, _x.rlt_velocity.z, _x.abs_valid, _x.abs_position.x, _x.abs_position.y, _x.abs_position.z, _x.abs_theta, _x.abs_velocity.x, _x.abs_velocity.y, _x.abs_velocity.z, _x.longitude_tag, _x.lateral_tag,) = _get_struct_iH3B4fB3df3dB3df3d2B().unpack(str[start:end])
      self.rlt_valid = bool(self.rlt_valid)
      self.abs_valid = bool(self.abs_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.predicted_traj = []
      for i in range(0, length):
        val1 = leadgen_msgs.msg.LeadgenWaypoint()
        _v3 = val1.point
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 40
        (_x.theta, _x.kappa, _x.station, _x.lateral, _x.speed, _x.accel,) = _get_struct_4d2f().unpack(str[start:end])
        _v4 = val1.time_arrival
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        self.predicted_traj.append(val1)
      start = end
      end += 4
      (self.predicted_period,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_iH3B4fB3df3dB3df3d2B().pack(_x.id, _x.source_sensor, _x.type, _x.status, _x.cutting, _x.length, _x.width, _x.height, _x.velocity_heading, _x.rlt_valid, _x.rlt_position.x, _x.rlt_position.y, _x.rlt_position.z, _x.rlt_theta, _x.rlt_velocity.x, _x.rlt_velocity.y, _x.rlt_velocity.z, _x.abs_valid, _x.abs_position.x, _x.abs_position.y, _x.abs_position.z, _x.abs_theta, _x.abs_velocity.x, _x.abs_velocity.y, _x.abs_velocity.z, _x.longitude_tag, _x.lateral_tag))
      length = len(self.predicted_traj)
      buff.write(_struct_I.pack(length))
      for val1 in self.predicted_traj:
        _v5 = val1.point
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_4d2f().pack(_x.theta, _x.kappa, _x.station, _x.lateral, _x.speed, _x.accel))
        _v6 = val1.time_arrival
        _x = _v6
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
      buff.write(_get_struct_f().pack(self.predicted_period))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rlt_position is None:
        self.rlt_position = geometry_msgs.msg.Point()
      if self.rlt_velocity is None:
        self.rlt_velocity = geometry_msgs.msg.Vector3()
      if self.abs_position is None:
        self.abs_position = geometry_msgs.msg.Point()
      if self.abs_velocity is None:
        self.abs_velocity = geometry_msgs.msg.Vector3()
      if self.predicted_traj is None:
        self.predicted_traj = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 133
      (_x.id, _x.source_sensor, _x.type, _x.status, _x.cutting, _x.length, _x.width, _x.height, _x.velocity_heading, _x.rlt_valid, _x.rlt_position.x, _x.rlt_position.y, _x.rlt_position.z, _x.rlt_theta, _x.rlt_velocity.x, _x.rlt_velocity.y, _x.rlt_velocity.z, _x.abs_valid, _x.abs_position.x, _x.abs_position.y, _x.abs_position.z, _x.abs_theta, _x.abs_velocity.x, _x.abs_velocity.y, _x.abs_velocity.z, _x.longitude_tag, _x.lateral_tag,) = _get_struct_iH3B4fB3df3dB3df3d2B().unpack(str[start:end])
      self.rlt_valid = bool(self.rlt_valid)
      self.abs_valid = bool(self.abs_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.predicted_traj = []
      for i in range(0, length):
        val1 = leadgen_msgs.msg.LeadgenWaypoint()
        _v7 = val1.point
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 40
        (_x.theta, _x.kappa, _x.station, _x.lateral, _x.speed, _x.accel,) = _get_struct_4d2f().unpack(str[start:end])
        _v8 = val1.time_arrival
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        self.predicted_traj.append(val1)
      start = end
      end += 4
      (self.predicted_period,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
_struct_iH3B4fB3df3dB3df3d2B = None
def _get_struct_iH3B4fB3df3dB3df3d2B():
    global _struct_iH3B4fB3df3dB3df3d2B
    if _struct_iH3B4fB3df3dB3df3d2B is None:
        _struct_iH3B4fB3df3dB3df3d2B = struct.Struct("<iH3B4fB3df3dB3df3d2B")
    return _struct_iH3B4fB3df3dB3df3d2B
_struct_4d2f = None
def _get_struct_4d2f():
    global _struct_4d2f
    if _struct_4d2f is None:
        _struct_4d2f = struct.Struct("<4d2f")
    return _struct_4d2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
