// Generated by gencpp from file ytthdmap_msgs/S_STOPLINE.msg
// DO NOT EDIT!


#ifndef YTTHDMAP_MSGS_MESSAGE_S_STOPLINE_H
#define YTTHDMAP_MSGS_MESSAGE_S_STOPLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ytthdmap_msgs/S_POINT.h>

namespace ytthdmap_msgs
{
template <class ContainerAllocator>
struct S_STOPLINE_
{
  typedef S_STOPLINE_<ContainerAllocator> Type;

  S_STOPLINE_()
    : offset(0)
    , latOffset(0)
    , type(0)
    , validnum(0)
    , point()  {
    }
  S_STOPLINE_(const ContainerAllocator& _alloc)
    : offset(0)
    , latOffset(0)
    , type(0)
    , validnum(0)
    , point()  {
  (void)_alloc;
      point.assign( ::ytthdmap_msgs::S_POINT_<ContainerAllocator> (_alloc));
  }



   typedef int16_t _offset_type;
  _offset_type offset;

   typedef int16_t _latOffset_type;
  _latOffset_type latOffset;

   typedef int16_t _type_type;
  _type_type type;

   typedef int16_t _validnum_type;
  _validnum_type validnum;

   typedef boost::array< ::ytthdmap_msgs::S_POINT_<ContainerAllocator> , 100>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> const> ConstPtr;

}; // struct S_STOPLINE_

typedef ::ytthdmap_msgs::S_STOPLINE_<std::allocator<void> > S_STOPLINE;

typedef boost::shared_ptr< ::ytthdmap_msgs::S_STOPLINE > S_STOPLINEPtr;
typedef boost::shared_ptr< ::ytthdmap_msgs::S_STOPLINE const> S_STOPLINEConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ytthdmap_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ytthdmap_msgs': ['/home/xiaotongfeng/Desktop/ROS_HDmap_Decision_L4/ros_system/src/ytthdmap/ytthdmap_msgs/./']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05414b44a3589a776a4ff3be4a793437";
  }

  static const char* value(const ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05414b44a3589a77ULL;
  static const uint64_t static_value2 = 0x6a4ff3be4a793437ULL;
};

template<class ContainerAllocator>
struct DataType< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ytthdmap_msgs/S_STOPLINE";
  }

  static const char* value(const ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 offset\n\
int16 latOffset\n\
int16 type\n\
int16 validnum\n\
S_POINT[100] point\n\
\n\
================================================================================\n\
MSG: ytthdmap_msgs/S_POINT\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset);
      stream.next(m.latOffset);
      stream.next(m.type);
      stream.next(m.validnum);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct S_STOPLINE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ytthdmap_msgs::S_STOPLINE_<ContainerAllocator>& v)
  {
    s << indent << "offset: ";
    Printer<int16_t>::stream(s, indent + "  ", v.offset);
    s << indent << "latOffset: ";
    Printer<int16_t>::stream(s, indent + "  ", v.latOffset);
    s << indent << "type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.type);
    s << indent << "validnum: ";
    Printer<int16_t>::stream(s, indent + "  ", v.validnum);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ytthdmap_msgs::S_POINT_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YTTHDMAP_MSGS_MESSAGE_S_STOPLINE_H
