(cl:in-package leadgen_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          SOURCE_SENSOR-VAL
          SOURCE_SENSOR
          TYPE-VAL
          TYPE
          STATUS-VAL
          STATUS
          CUTTING-VAL
          CUTTING
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          VELOCITY_HEADING-VAL
          VELOCITY_HEADING
          RLT_VALID-VAL
          RLT_VALID
          RLT_POSITION-VAL
          RLT_POSITION
          RLT_THETA-VAL
          RLT_THETA
          RLT_VELOCITY-VAL
          RLT_VELOCITY
          ABS_VALID-VAL
          ABS_VALID
          ABS_POSITION-VAL
          ABS_POSITION
          ABS_THETA-VAL
          ABS_THETA
          ABS_VELOCITY-VAL
          ABS_VELOCITY
))