(cl:defpackage leadgen_msgs-msg
  (:use )
  (:export
   "<LEADGENCHASSIS>"
   "LEADGENCHASSIS"
   "<LEADGENHMI>"
   "LEADGENHMI"
   "<LEADGENOBSINPUTARRAY>"
   "LEADGENOBSINPUTARRAY"
   "<LEADGENOBSTACLEINPUT>"
   "LEADGENOBSTACLEINPUT"
   "<LEADGENOBSTACLEOUTPUT>"
   "LEADGENOBSTACLEOUTPUT"
   "<LEADGENPOINTARRAY>"
   "LEADGENPOINTARRAY"
   "<LEADGENSTATUS>"
   "LEADGENSTATUS"
   "<LEADGENTRAJECTORY>"
   "LEADGENTRAJECTORY"
   "<LEADGENWAYPOINT>"
   "LEADGENWAYPOINT"
  ))

