# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planning_msgs/PathPoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PathPoint(genpy.Message):
  _md5sum = "8ca146211c0eeacb11ce47c4386e83c5"
  _type = "planning_msgs/PathPoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 time
float64 x
float64 y
float64 z
float64 theta
float64 curvature
float64 curv_rate
float32 velocity 
float32 acceleration 
float32 s
float32 l
"""
  __slots__ = ['time','x','y','z','theta','curvature','curv_rate','velocity','acceleration','s','l']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,x,y,z,theta,curvature,curv_rate,velocity,acceleration,s,l

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PathPoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.theta is None:
        self.theta = 0.
      if self.curvature is None:
        self.curvature = 0.
      if self.curv_rate is None:
        self.curv_rate = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.acceleration is None:
        self.acceleration = 0.
      if self.s is None:
        self.s = 0.
      if self.l is None:
        self.l = 0.
    else:
      self.time = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.theta = 0.
      self.curvature = 0.
      self.curv_rate = 0.
      self.velocity = 0.
      self.acceleration = 0.
      self.s = 0.
      self.l = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d4f().pack(_x.time, _x.x, _x.y, _x.z, _x.theta, _x.curvature, _x.curv_rate, _x.velocity, _x.acceleration, _x.s, _x.l))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.time, _x.x, _x.y, _x.z, _x.theta, _x.curvature, _x.curv_rate, _x.velocity, _x.acceleration, _x.s, _x.l,) = _get_struct_7d4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d4f().pack(_x.time, _x.x, _x.y, _x.z, _x.theta, _x.curvature, _x.curv_rate, _x.velocity, _x.acceleration, _x.s, _x.l))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.time, _x.x, _x.y, _x.z, _x.theta, _x.curvature, _x.curv_rate, _x.velocity, _x.acceleration, _x.s, _x.l,) = _get_struct_7d4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d4f = None
def _get_struct_7d4f():
    global _struct_7d4f
    if _struct_7d4f is None:
        _struct_7d4f = struct.Struct("<7d4f")
    return _struct_7d4f
