# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ytthdmap_msgs/S_LANEINFO.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ytthdmap_msgs.msg

class S_LANEINFO(genpy.Message):
  _md5sum = "6a14e40ee54202dfeea4f9379da90309"
  _type = "ytthdmap_msgs/S_LANEINFO"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """S_LINE centerline
S_LINE leftboundry
S_LINE rightboundry
float32 width
bool IsPartofRouting
int16 type
int16 direction
int16 id
float32 length

================================================================================
MSG: ytthdmap_msgs/S_LINE
int16 type
int16[100] linetype
S_POINT[100] point
int16 pointnum

================================================================================
MSG: ytthdmap_msgs/S_POINT
float32 x
float32 y
float32 z
"""
  __slots__ = ['centerline','leftboundry','rightboundry','width','IsPartofRouting','type','direction','id','length']
  _slot_types = ['ytthdmap_msgs/S_LINE','ytthdmap_msgs/S_LINE','ytthdmap_msgs/S_LINE','float32','bool','int16','int16','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       centerline,leftboundry,rightboundry,width,IsPartofRouting,type,direction,id,length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(S_LANEINFO, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.centerline is None:
        self.centerline = ytthdmap_msgs.msg.S_LINE()
      if self.leftboundry is None:
        self.leftboundry = ytthdmap_msgs.msg.S_LINE()
      if self.rightboundry is None:
        self.rightboundry = ytthdmap_msgs.msg.S_LINE()
      if self.width is None:
        self.width = 0.
      if self.IsPartofRouting is None:
        self.IsPartofRouting = False
      if self.type is None:
        self.type = 0
      if self.direction is None:
        self.direction = 0
      if self.id is None:
        self.id = 0
      if self.length is None:
        self.length = 0.
    else:
      self.centerline = ytthdmap_msgs.msg.S_LINE()
      self.leftboundry = ytthdmap_msgs.msg.S_LINE()
      self.rightboundry = ytthdmap_msgs.msg.S_LINE()
      self.width = 0.
      self.IsPartofRouting = False
      self.type = 0
      self.direction = 0
      self.id = 0
      self.length = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_h().pack(self.centerline.type))
      buff.write(_get_struct_100h().pack(*self.centerline.linetype))
      for val1 in self.centerline.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_2h().pack(_x.centerline.pointnum, _x.leftboundry.type))
      buff.write(_get_struct_100h().pack(*self.leftboundry.linetype))
      for val1 in self.leftboundry.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_2h().pack(_x.leftboundry.pointnum, _x.rightboundry.type))
      buff.write(_get_struct_100h().pack(*self.rightboundry.linetype))
      for val1 in self.rightboundry.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_hfB3hf().pack(_x.rightboundry.pointnum, _x.width, _x.IsPartofRouting, _x.type, _x.direction, _x.id, _x.length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.centerline is None:
        self.centerline = ytthdmap_msgs.msg.S_LINE()
      if self.leftboundry is None:
        self.leftboundry = ytthdmap_msgs.msg.S_LINE()
      if self.rightboundry is None:
        self.rightboundry = ytthdmap_msgs.msg.S_LINE()
      end = 0
      start = end
      end += 2
      (self.centerline.type,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 200
      self.centerline.linetype = _get_struct_100h().unpack(str[start:end])
      self.centerline.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.centerline.point.append(val1)
      _x = self
      start = end
      end += 4
      (_x.centerline.pointnum, _x.leftboundry.type,) = _get_struct_2h().unpack(str[start:end])
      start = end
      end += 200
      self.leftboundry.linetype = _get_struct_100h().unpack(str[start:end])
      self.leftboundry.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.leftboundry.point.append(val1)
      _x = self
      start = end
      end += 4
      (_x.leftboundry.pointnum, _x.rightboundry.type,) = _get_struct_2h().unpack(str[start:end])
      start = end
      end += 200
      self.rightboundry.linetype = _get_struct_100h().unpack(str[start:end])
      self.rightboundry.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.rightboundry.point.append(val1)
      _x = self
      start = end
      end += 17
      (_x.rightboundry.pointnum, _x.width, _x.IsPartofRouting, _x.type, _x.direction, _x.id, _x.length,) = _get_struct_hfB3hf().unpack(str[start:end])
      self.IsPartofRouting = bool(self.IsPartofRouting)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_h().pack(self.centerline.type))
      buff.write(self.centerline.linetype.tostring())
      for val1 in self.centerline.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_2h().pack(_x.centerline.pointnum, _x.leftboundry.type))
      buff.write(self.leftboundry.linetype.tostring())
      for val1 in self.leftboundry.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_2h().pack(_x.leftboundry.pointnum, _x.rightboundry.type))
      buff.write(self.rightboundry.linetype.tostring())
      for val1 in self.rightboundry.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_hfB3hf().pack(_x.rightboundry.pointnum, _x.width, _x.IsPartofRouting, _x.type, _x.direction, _x.id, _x.length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.centerline is None:
        self.centerline = ytthdmap_msgs.msg.S_LINE()
      if self.leftboundry is None:
        self.leftboundry = ytthdmap_msgs.msg.S_LINE()
      if self.rightboundry is None:
        self.rightboundry = ytthdmap_msgs.msg.S_LINE()
      end = 0
      start = end
      end += 2
      (self.centerline.type,) = _get_struct_h().unpack(str[start:end])
      start = end
      end += 200
      self.centerline.linetype = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=100)
      self.centerline.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.centerline.point.append(val1)
      _x = self
      start = end
      end += 4
      (_x.centerline.pointnum, _x.leftboundry.type,) = _get_struct_2h().unpack(str[start:end])
      start = end
      end += 200
      self.leftboundry.linetype = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=100)
      self.leftboundry.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.leftboundry.point.append(val1)
      _x = self
      start = end
      end += 4
      (_x.leftboundry.pointnum, _x.rightboundry.type,) = _get_struct_2h().unpack(str[start:end])
      start = end
      end += 200
      self.rightboundry.linetype = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=100)
      self.rightboundry.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.rightboundry.point.append(val1)
      _x = self
      start = end
      end += 17
      (_x.rightboundry.pointnum, _x.width, _x.IsPartofRouting, _x.type, _x.direction, _x.id, _x.length,) = _get_struct_hfB3hf().unpack(str[start:end])
      self.IsPartofRouting = bool(self.IsPartofRouting)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
_struct_hfB3hf = None
def _get_struct_hfB3hf():
    global _struct_hfB3hf
    if _struct_hfB3hf is None:
        _struct_hfB3hf = struct.Struct("<hfB3hf")
    return _struct_hfB3hf
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_100h = None
def _get_struct_100h():
    global _struct_100h
    if _struct_100h is None:
        _struct_100h = struct.Struct("<100h")
    return _struct_100h
