# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ytthdmap_msgs/S_STOPLINE.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ytthdmap_msgs.msg

class S_STOPLINE(genpy.Message):
  _md5sum = "05414b44a3589a776a4ff3be4a793437"
  _type = "ytthdmap_msgs/S_STOPLINE"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 offset
int16 latOffset
int16 type
int16 validnum
S_POINT[100] point

================================================================================
MSG: ytthdmap_msgs/S_POINT
float32 x
float32 y
float32 z
"""
  __slots__ = ['offset','latOffset','type','validnum','point']
  _slot_types = ['int16','int16','int16','int16','ytthdmap_msgs/S_POINT[100]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       offset,latOffset,type,validnum,point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(S_STOPLINE, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.offset is None:
        self.offset = 0
      if self.latOffset is None:
        self.latOffset = 0
      if self.type is None:
        self.type = 0
      if self.validnum is None:
        self.validnum = 0
      if self.point is None:
        self.point = [ytthdmap_msgs.msg.S_POINT() for _ in range(100)]
    else:
      self.offset = 0
      self.latOffset = 0
      self.type = 0
      self.validnum = 0
      self.point = [ytthdmap_msgs.msg.S_POINT() for _ in range(100)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4h().pack(_x.offset, _x.latOffset, _x.type, _x.validnum))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.offset, _x.latOffset, _x.type, _x.validnum,) = _get_struct_4h().unpack(str[start:end])
      self.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4h().pack(_x.offset, _x.latOffset, _x.type, _x.validnum))
      for val1 in self.point:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.offset, _x.latOffset, _x.type, _x.validnum,) = _get_struct_4h().unpack(str[start:end])
      self.point = []
      for i in range(0, 100):
        val1 = ytthdmap_msgs.msg.S_POINT()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4h = None
def _get_struct_4h():
    global _struct_4h
    if _struct_4h is None:
        _struct_4h = struct.Struct("<4h")
    return _struct_4h
